services:
  - type: web
    name: noteverse
    runtime: node
    rootDir: Back_End
    buildCommand: npm install && npm install --prefix ../Front_End && npm run build --prefix ../Front_End
    startCommand: npm run start:render
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
